provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  pigo-face-detector:
    lang: go
    handler: ./pigo-openfaas
    image: localhost:5000/pigo-openfaas:0.1
    environment:
      input_mode: "url"
      output_mode: "image"